comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  hide_project_coverage: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
